name: Validate assets

on:
  push:
    paths:
      - ${{ github.paths }}
  pull_request:
    paths:
      - ${{ github.paths }}
  workflow_dispatch:

env:
  paths: assets/json/fontawesome.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that fontawesome.json is sorted
        run: |
          for json in ${{ github.paths }} ; do
            diff <(jq -S . $json) $json || exit 1
          done
